version: '3.8'
services:
  web:
    container_name: api
    build:
      context: ./
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
      - "7070:7070"
    environment:
      - CONFIG=config/config-docker
    depends_on:
      - redis
    restart: always
    volumes:
      - ./:/app
    networks:
      - rest-company
  redis:
    image: redis/redis-stack:latest
    restart: always
    ports:
      - '6379:6379'
      - '8001:8001'
    volumes:
      - ./local-data/:/data
    networks:
      - rest-company
volumes:
  cache:
    driver: local
networks:
  rest-company:
    driver: bridge